# Generated by Django 4.2.8 on 2024-02-01 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('paragraph', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('paragraph_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_indexer.paragraph')),
            ],
            options={
                'indexes': [models.Index(fields=['word', 'paragraph_word'], name='text_indexe_word_f48a13_idx')],
            },
        ),
    ]
